version: '3'
services:
  ui-gg:
    image: ui-gg
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf # Override to make local development faster (no rebuilds for config changes)
