image: onelouder/alpine-nodejs-docker
buildTool: docker
branches:
  - ALL
stages:
  - name: build
    script:
      - bash npm_build.sh intchngfe
      - bash npm_build.sh mohfe
      - bash npm_build.sh Tier3
  - name: docker build
    script:
      - mkdir -p build
      - cp Dockerfile build
      - cp -R nginx build
      - cp -R intchngfe/build build/intchngfe
      - cp -R mohfe/build build/mohfe
      - cp -R Tier3/build build/Tier3
      - docker build --tag global-good/report-tools --build-arg CONT_BUILD_SHA=11111 build
  - name: tag & push
    script:
      - docker tag global-good/report-tools:latest docker.metaverse.l11.com/global-good/report-tools:$GIT_HASH_SHORT
      - docker tag global-good/report-tools:latest docker.metaverse.l11.com/global-good/report-tools:latest
      - docker push docker.metaverse.l11.com/global-good/report-tools:$GIT_HASH_SHORT
      - docker push docker.metaverse.l11.com/global-good/report-tools:latest
  - name: push to azure
    script:
      - docker tag global-good/report-tools:latest l11gg.azurecr.io/reporting/report-tools:$GIT_HASH_SHORT
      - docker tag global-good/report-tools:latest l11gg.azurecr.io/reporting/report-tools:latest
      - docker push l11gg.azurecr.io/reporting/report-tools:$GIT_HASH_SHORT
      - docker push l11gg.azurecr.io/reporting/report-tools:latest
  - name: deploy!
    trigger:
      branches:
        - master 
    script:
      - ssh -i ~/.ssh/GG_SSH_KEY level11@20.36.19.106 ./do-deploy.sh
  - name: bvt test
    trigger:
      branches:
        - master 
    script:
      - apk update; apk add openssh
      - ssh -i ~/.ssh/pe_id_rsa leveler@10.1.73.141 -tt "docker exec -it v8-server sh -c \"./valid8.sh --project=1 --test_plan=271 --configurations='bvt,chrome,remote_on\&65'\""
