image: onelouder/alpine-nodejs-docker
buildTool: docker
branches:
  - ALL
stages:
  - name: npm build
    script:
      - bash npm_build.sh intchngfe
      - bash npm_build.sh mohfe
  - name: docker build
    script:
      - mkdir -p build
      - cp Dockerfile build
      - cp -R nginx build
      - cp -R intchngfe/build build/intchngfe
      - cp -R mohfe/build build/mohfe
      - docker build --tag global-good/report-tools --build-arg CONT_BUILD_SHA=11111 build
  - name: tag & push
    script:
      - docker tag global-good/report-tools:latest docker.metaverse.l11.com/global-good/report-tools:$GIT_HASH_SHORT
      - docker tag global-good/report-tools:latest docker.metaverse.l11.com/global-good/report-tools:latest
      - docker push docker.metaverse.l11.com/global-good/report-tools:$GIT_HASH_SHORT
      - docker push docker.metaverse.l11.com/global-good/report-tools:latest
  - name: push to azure
    script:
      - docker tag global-good/report-tools:latest l11gg.azurecr.io/reporting/report-tools:$GIT_HASH_SHORT
      - docker tag global-good/report-tools:latest l11gg.azurecr.io/reporting/report-tools:latest
      - docker push l11gg.azurecr.io/reporting/report-tools:$GIT_HASH_SHORT
      - docker push l11gg.azurecr.io/reporting/report-tools:latest
