export const dstyles = {
  headline: {
    fontSize: 24,
    paddingTop: 16,
    marginBottom: 12,
    fontWeight: 400,
  },
  idBar: {
    backgroundColor: '#51326c',
    width: '100%',
    textAlign: 'center',
    paddingTop: '14px',
    paddingBottom: '24px',
    lineHeight: '30px',
    color: 'white',
  },
  idBarH: {
    fontWeight: '500',
    marginTop: '20px',
    marginBottom: '40px',
  },
  wrapwrap: {
    width: '100%',
    margin: '0 auto',
    marginTop: '-48px'
  },
  wrapTabs: {
    width: '80vw',
    margin: '0 auto',
  },
  tabMod: {
    marginTop: '-48px',
  },
  deviceTableHeader: {
    margin: "0",
  },
  halfCard: {
    width: '48%',
    margin: '24px 1%',
    display: 'inline-block',
    verticalAlign: 'top',
  },
  thirdCard: {
    width: '31%',
    margin: '24px 1%',
    display: 'inline-block',
    verticalAlign: 'top',
  },
  fourthCard: {
    width: '23%',
    margin: '24px 1%',
    display: 'inline-block',
    verticalAlign: 'top',
  },
  greendot: {
    height: '20px',
    width: '20px',
    backgroundColor: 'green',
    border: '1px solid #aaa',
    borderRadius: '20px',
    margin: '0 auto',
  },
  yellowdot: {
    height: '20px',
    width: '20px',
    backgroundColor: 'yellow',
    border: '1px solid #aaa',
    borderRadius: '20px',
    margin: '0 auto',
  },
  reddot: {
    height: '20px',
    width: '20px',
    backgroundColor: 'red',
    border: '1px solid #aaa',
    borderRadius: '20px',
    margin: '0 auto',
  },
  cleardot: {
    height: '20px',
    width: '20px',
    backgroundColor: 'white',
    border: '1px solid #aaa',
    borderRadius: '20px',
    margin: '0 auto',
  },
  coldtemp: {
    padding: '5px',
    backgroundColor: 'skyblue',
    color: 'white',
    maxWidth: '50px',
    textAlign: 'center',
    borderRadius: '4px',
  },
  hottemp: {
    padding: '5px',
    backgroundColor: 'red',
    color: 'white',
    maxWidth: '50px',
    textAlign: 'center',
    borderRadius: '4px',
  },
  warntemp: {
    padding: '5px',
    backgroundColor: 'orange',
    color: 'white',
    maxWidth: '50px',
    textAlign: 'center',
    borderRadius: '4px',
  },
  goodtemp: {
    padding: '5px',
    backgroundColor: 'white',
    color: 'black',
    maxWidth: '50px',
    textAlign: 'center',
    borderRadius: '4px',
  },
  middlePane: {
    flex: '1'
  },
  redPing: {
    padding: '5px',
    backgroundColor: 'red',
    color: 'white',
    maxWidth: '80px',
    textAlign: 'center',
    borderRadius: '4px',
  },
  clearPing: {
    padding: '5px',
    backgroundColor: 'white',
    color: 'black',
    maxWidth: '80px',
    textAlign: 'center',
    borderRadius: '4px',
  },
  statusColumn: {
    width: '50px',
    textAlign: 'center',
    paddingLeft: '2px',
    paddingRight: '2px',
  },
  deviceColumn: {
    width: '150px',
    paddingLeft: '2px',
    paddingRight: '2px',
  },
  localeColumn: {
    width: '150px',
    paddingLeft: '2px',
    paddingRight: '2px',
  },
  holdoverColumn: {
    width: '50px',
    paddingLeft: '2px',
    paddingRight: '2px',
  },
  lastpingColumn: {
      width: '80px',
      paddingLeft: '2px',
      paddingRight: '2px',
      textAlign: 'center',
  },
};
